### ISSUE TITLE
variable is used before it is initialized

### ISSUE THREAD

**Issue by yvikhlya** [BreakawayLabs/mom#101]
In ocean_density.F90 global variable neutralrho_interval_r is initialized at line 1286, after it is used in compute_diagnostic_factors(...) which is called at line 1159. This causes model to crash when using intel compiler with -g option.

**Comment by nicjhan** [comment]
HI @yvikhlya thanks a lot for this. Do you think you could make the fix and do a pull request?

**Comment by yvikhlya** [comment]
Hi Nic,

I made a dirty fix to keep my simulation going, but I don't think it is good enough to be included into distribution. I will look into this issue, and try to come up with better fix. I need to understand a logic of ocean_density module.

**Comment by yvikhlya** [comment]
Pull request sent.

**Comment by nicjhan** [comment]
@yvikhlya we merged this. Thank you for your contribution.
