### ISSUE TITLE
ESM2M_pi-control_C2 floating invalid

### ISSUE THREAD

**Issue by nicjhan** [BreakawayLabs/mom#141]
The ESM2M_pi-control_C2 fails with floating invalid in mg_drag, suspect this is due to unusual where statement behaviour.

**Comment by aidanheerdegen** [comment]
Was there an error in the where formulation? I've been getting a lot of floating point errors that go away when I put in debug checks, which makes me think there is a compiler optimisation problem. No necessarily where statements, but this sounded very similar.

**Comment by nicjhan** [comment]
@aidanheerdegen at first I was sure this was a problem with the code. The exception went away when I switched from 'where' to 'do loop' constructs. However later I found that there were many of these exceptions (> 5) all happening within where statements. These all went away when I upgraded the compiler version in #143 .

**Comment by aidanheerdegen** [comment]
Ah ha! Ping @marshallward

**Comment by marshallward** [comment]
Yikes... definitely looks like the reason.

I can't find any mention of it in the release notes, but maybe Intel is not so forthright with its bug fixes.
